parameters:
    toolchain: ''

jobs:
    - job: ${{ parameters.name }}
      pool:
          vmImage: ${{ parameters.vmImage }}

      steps:
          - template: install-rust.yml
            parameters:
                toolchain: ${{ parameters.toolchain }}

          - script: |
                cargo +${{ parameters.toolchain }} build --all
            displayName: Build sources

          - script: |
                cargo +${{ parameters.toolchain }} check --all --no-default-features --features runtime-async-std
            condition: eq('${{ parameters.toolchain }}', 'nightly')
            displayName: Build with async-std toolchain

          - script: |
                cargo +${{ parameters.toolchain }} test --all --no-fail-fast -- --nocapture
            condition: eq('${{ parameters.toolchain }}', 'nightly')
            displayName: Run tests (nightly only)
